language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=nightly WP_MULTISITE=0

before_script:
  - composer install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - bash bin/build.sh

script: phpunit
